package model

// SNMPVersion enum.
type SNMPVersion string

const (
	SNMPv2c SNMPVersion = "v2c"
	SNMPv3  SNMPVersion = "v3"
)

// SNMPConfig is the top-level SNMP configuration for one device.
type SNMPConfig struct {
	// System metadata (rendered into sysContact/sysLocation).
	Contact     string `json:"contact,omitempty"`
	Location    string `json:"location,omitempty"`
	Description string `json:"description,omitempty"`
	// Listen config.
	ListenAddresses []string `json:"listen_addresses,omitempty"` // e.g. ["127.0.0.1", "10.0.0.1"]
	ListenPort      int      `json:"listen_port,omitempty"`      // default 161
	// Access control.
	Communities []SNMPCommunity `json:"communities,omitempty"`
	V3Users     []SNMPV3User    `json:"v3_users,omitempty"`
	V3Groups    []SNMPV3Group   `json:"v3_groups,omitempty"`
	V3Views     []SNMPV3View    `json:"v3_views,omitempty"`
	// Traps.
	TrapTargets []SNMPTrapTarget `json:"trap_targets,omitempty"`
	// Engine identity (required for v3 on VyOS 1.5; auto-generated by the UI
	// if blank on first commit to avoid a backend error).
	EngineID string `json:"engine_id,omitempty"`
	// VRF binding for SNMP agent / polling. "" = default VRF.
	VRF string `json:"vrf,omitempty"`
}

// SNMPCommunity is an SNMPv2c community string. Insecure — v2c sends the
// community in plaintext on every request. Only available on non-production
// devices; vyos-cp will reject commits that set v2c on devices tagged
// "production".
type SNMPCommunity struct {
	Name          string   `json:"name"`                     // the community string itself
	Authorization string   `json:"authorization,omitempty"`  // "ro" | "rw"
	Clients       []string `json:"clients,omitempty"`        // allowed source IPs/CIDRs
	Network       []string `json:"network,omitempty"`        // networks allowed to query
}

// SNMPV3User is an authenticated/encrypted v3 user. Required for production.
type SNMPV3User struct {
	Name          string `json:"name"`
	Group         string `json:"group,omitempty"`          // binds user -> group -> view -> OID tree
	AuthProtocol  string `json:"auth_protocol,omitempty"`  // "sha" | "md5" (md5 deprecated, reject)
	AuthPassword  string `json:"auth_password,omitempty"`  // plaintext: write-only from UI; cleared by decoder
	AuthEncrypted string `json:"auth_encrypted,omitempty"` // hashed: round-tripped on edit, never shown to user
	PrivProtocol  string `json:"priv_protocol,omitempty"`  // "aes" | "aes128" | "aes256"
	PrivPassword  string `json:"priv_password,omitempty"`  // plaintext: write-only from UI
	PrivEncrypted string `json:"priv_encrypted,omitempty"` // hashed: round-tripped on edit
	EngineID      string `json:"engine_id,omitempty"`
	// TPMode is "auth" (authNoPriv), "priv" (authPriv), or "no-auth".
	// For secure deployments only "priv" is allowed; vyos-cp warns on the others.
	TPMode string `json:"tp_mode,omitempty"`
}

// SNMPV3Group binds a security model to a view and access level.
type SNMPV3Group struct {
	Name     string `json:"name"`
	Mode     string `json:"mode"` // "ro" | "rw"
	SecLevel string `json:"sec_level,omitempty"` // "auth" | "priv" | "no-auth"
	View     string `json:"view,omitempty"`
}

// SNMPV3View is a filter over the OID tree.
type SNMPV3View struct {
	Name  string   `json:"name"`
	OIDs  []string `json:"oids,omitempty"`  // "1.3.6.1.2.1.1"
	Mask  string   `json:"mask,omitempty"`
	Exclude bool   `json:"exclude,omitempty"` // default is include
}

// SNMPTrapTarget is an NMS/SIEM receiver.
type SNMPTrapTarget struct {
	Address   string      `json:"address"`              // IP or hostname
	Port      int         `json:"port,omitempty"`       // default 162
	Version   SNMPVersion `json:"version"`              // v2c | v3
	// v2c field:
	Community string `json:"community,omitempty"`
	// v3 fields (mutually exclusive with Community):
	V3User    string `json:"v3_user,omitempty"`
	V3EngineID string `json:"v3_engine_id,omitempty"`
	// Common.
	Type      string `json:"type,omitempty"` // "trap" | "inform"
}
